version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - GROQ_API_KEY=sk-your-groq-api-key
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
